/**
 * Fetches the eBay API Status RSS feed and writes the latest items to docs/API_STATUS.md.
 * Used by the GitHub Action to keep an in-repo snapshot. Run with: npx tsx src/scripts/updateApiStatusDoc.ts
 */

import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { getApiStatusFeed, type ApiStatusItem } from '@/utils/apiStatusFeed.js';
import { getErrorMessage } from '@/utils/errors.js';
import { Data, Effect, Either } from 'effect';
import process from 'node:process';

const DEFAULT_LIMIT = 15;
const OUT_PATH = join(process.cwd(), 'docs', 'API_STATUS.md');

/** Tagged failure raised while updating the checked-in API status snapshot. */
class ApiStatusDocUpdateError extends Data.TaggedError('ApiStatusDocUpdateError')<{
  /** Human-readable script failure message. */
  readonly message: string;
  /** Lower-level feed or filesystem cause. */
  readonly cause?: unknown;
}> {}

function escapeCell(s: string): string {
  return s.replace(/\|/g, '\\|').replace(/\n/g, ' ');
}

function buildMarkdown(items: ApiStatusItem[]): string {
  const lines: string[] = [
    '# eBay API Status (latest)',
    '',
    'Auto-updated snapshot from the [eBay API Status RSS feed](https://developer.ebay.com/rss/api-status).',
    'Full list: [developer.ebay.com/support/api-status](https://developer.ebay.com/support/api-status).',
    '',
    `*Last updated: ${new Date().toISOString()}*`,
    '',
    '| Title | API | Site | Status | Last updated | Link |',
    '|-------|-----|------|--------|--------------|------|',
  ];

  for (const item of items) {
    const link = item.link ? `[Details](${item.link})` : '';
    lines.push(
      `| ${escapeCell(item.title)} | ${escapeCell(item.api)} | ${escapeCell(item.site)} | ${escapeCell(item.status)} | ${escapeCell(item.lastUpdated)} | ${link} |`,
    );
  }

  lines.push(
    '',
    '---',
    '',
    '*Generated by [ebay-mcp](https://github.com/YosefHayim/ebay-mcp) API status sync.*',
  );
  return lines.join('\n');
}

const updateApiStatusDoc = (): Effect.Effect<number, ApiStatusDocUpdateError> =>
  Effect.gen(function* () {
    const { items, error } = yield* getApiStatusFeed({ limit: DEFAULT_LIMIT }).pipe(
      Effect.mapError(
        (cause) =>
          new ApiStatusDocUpdateError({
            message: 'Failed to fetch API status feed',
            cause,
          }),
      ),
    );

    if (error && items.length === 0) {
      return yield* Effect.fail(
        new ApiStatusDocUpdateError({
          message: `Failed to fetch API status feed: ${error}`,
          cause: error,
        }),
      );
    }

    const markdown = buildMarkdown(items);
    yield* Effect.try({
      try: () => writeFileSync(OUT_PATH, markdown, 'utf8'),
      catch: (cause) =>
        new ApiStatusDocUpdateError({
          message: `Failed to write API status doc to ${OUT_PATH}`,
          cause,
        }),
    });

    return items.length;
  });

async function main(): Promise<void> {
  const count = await Effect.runPromise(updateApiStatusDoc());
  console.log(`Wrote ${count} items to ${OUT_PATH}`);
}

void Effect.runPromise(
  Effect.either(
    Effect.tryPromise({
      try: main,
      catch: (error) => error,
    }),
  ),
).then((result) => {
  if (Either.isLeft(result)) {
    console.error(getErrorMessage(result.left, String(result.left)));
    process.exitCode = 1;
  }
});
